# -*- coding: utf-8 -*-
"""hash generator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXvrzrpWiT7kvjJJoLZ9qfAcvMp8wdPf
"""

import hashlib

text = input("Enter text to hash: ")
hash_object = hashlib.sha256(text.encode())
print("SHA256 Hash:", hash_object.hexdigest())